---
version: '3'

services:

  zammad-backup:
    command: ["zammad-backup"]
    depends_on:
      - zammad-railsserver
      - zammad-postgresql
    entrypoint: /usr/local/bin/backup.sh
    environment:
      - BACKUP_SLEEP=86400
      - HOLD_DAYS=10
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASS}
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    restart: ${RESTART}
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 25M
    volumes:
      - /home/webelight-004/zammad-backup:/var/tmp/zammad
      - /home/webelight-004/zammad-data:/opt/zammad


  zammad-init:
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    environment:
      - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_PASS=${POSTGRES_PASS}
      - REDIS_URL=${REDIS_URL}
    image: ${IMAGE_REPO}:zammad${VERSION}
    restart: on-failure
    deploy:
        resources:
          limits:
            memory: 100M
          reservations:
             memory: 50M  
    volumes:
      - /home/webelight-004/zammad-data:/opt/zammad
  zammad-elasticsearch:
    environment:
      - discovery.type=single-node
    image: ${IMAGE_REPO}:zammad-elasticsearch${VERSION}
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 8500M
          reservations:
             memory: 5000M  
    volumes:
      - /home/webelight-004/elasticsearch-data:/usr/share/elasticsearch/data

  zammad-memcached:
    command: memcached -m 256M
    image: memcached:1.6.10-alpine
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 50M
          reservations:
             memory: 25M  

  zammad-nginx:
    command: ["zammad-nginx"]
    expose:
      - "8080"
    depends_on:
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 75M
          reservations:
             memory: 50M  
    volumes:
      - /home/webelight-004/zammad-data:/opt/zammad

  zammad-postgresql:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 512M
          reservations:
             memory: 100M  
    volumes:
      - /home/webelight-004/postgresql-data:/var/lib/postgresql/data

  zammad-railsserver:
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
    environment:
      - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
      - REDIS_URL=${REDIS_URL}
    image: ${IMAGE_REPO}:zammad${VERSION}
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 450M
          reservations:
             memory: 350M  
    volumes:
      - /home/webelight-004/zammad-data:/opt/zammad

  zammad-redis:
    image: redis:6.2.5-alpine
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 15M
          reservations:
             memory: 10M  

  zammad-scheduler:
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
      - zammad-redis
    environment:
      - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
      - REDIS_URL=${REDIS_URL}
    image: ${IMAGE_REPO}:zammad${VERSION}
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 335M
          reservations:
             memory: 270M  
    volumes:
      - /home/webelight-004/zammad-data:/opt/zammad

  zammad-websocket:
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
      - zammad-redis
    environment:
      - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
      - REDIS_URL=${REDIS_URL}
    image: ${IMAGE_REPO}:zammad${VERSION}
    restart: ${RESTART}
    deploy:
        resources:
          limits:
            memory: 250M
          reservations:
             memory: 175M  
    volumes:
      - /home/webelight-004/zammad-data:/opt/zammad

